id = "neocmake"
name = "NeoCMake"
version = "0.0.3"
schema_version = 1
authors = ["voiddog <voiddog@foxmail.com>"]
description = "CMake grammar and lsp with neocmakelsp"
repository = "https://github.com/voiddog/zed_neocmake"

[language_servers.cmake]
name = "neocmakelsp"
language = "CMake"

[grammars.cmake]
repository = "https://github.com/voiddog/zed_neocmake"
commit = "ad6aed284505f660d844a27797d9138134db2613"      # v0.3.0
