id = "neocmake"
name = "NeoCMake"
version = "0.0.3"
schema_version = 1
authors = ["voiddog <voiddog@foxmail.com>"]
description = "CMake grammar and lsp with neocmakelsp"
repository = "https://github.com/voiddog/zed_neocmake"

[language_servers.cmake]
name = "neocmakelsp"
language = "CMake"

[grammars.cmake]
repository = "https://github.com/voiddog/zed_neocmake"
commit = "bbeca41e5f3c05e84dd2d26f5b5acfeba984c916"      # v0.3.0
